name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version number
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            davidecavestro/gphotos-cdp:dev-main
            davidecavestro/gphotos-cdp:${{ github.sha }}
        if: github.ref == 'refs/heads/main'

      - name: Build and push tagged Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            davidecavestro/gphotos-cdp:${{ env.VERSION }}
            davidecavestro/gphotos-cdp:latest
        if: startsWith(github.ref, 'refs/tags/')
