name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Extract version number
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            davidecavestro/gphotos-cdp:dev-main
            davidecavestro/gphotos-cdp:${{ github.sha }}
            ghcr.io/davidecavestro/gphotos-cdp:dev-main
            ghcr.io/davidecavestro/gphotos-cdp:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
        if: github.ref == 'refs/heads/main'

      - name: Build and push tagged Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            davidecavestro/gphotos-cdp:${{ env.VERSION }}
            davidecavestro/gphotos-cdp:latest
            ghcr.io/davidecavestro/gphotos-cdp:${{ env.VERSION }}
            ghcr.io/davidecavestro/gphotos-cdp:latest
        if: startsWith(github.ref, 'refs/tags/')

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: davidecavestro/gphotos-cdp
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: v${{ github.ref_name }}
          body: |
            This release provides the container image:
            `davidecavestro/gphotos-cdp:${{ github.ref_name }}`
            ${{ steps.changelog.outputs.changes }}
          draft: false
          prerelease: false

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md